### PR TITLE
remove Mock::Quick

### PR DESCRIPTION
**Pull request by hvoers**
It is not used.

### CODE REVIEW

**Comment by hvoers** [comment]
Where did LDAP came from? It wasn't there in version 0.30.

It should be just one of the external providers.

**Comment by hvoers** [comment]
Please make a 0.41 release.

**Comment by bigpresh** [comment]
Actually, yes, I recall that the LDAP provider was planned to be a separate dist, but that hasn't happeened yet.  When I have a moment I'll create a new dist (unless @ofosos wishes to do so as it was his code!), then get a new DPAE release without that provider on CPAN.

**Comment by bigpresh** [comment]
I've merged another PR that improves the LDAP provider, so this now conflicts.

Once I've had a chance to rip out the LDAP provider into a separate dist and release it to CPAN, I'll remove Mock::Quick manually and get a new DPAE release out.

**Pull request closed without merging**
