### PR TITLE
attempt to make LDAP provider to work with generic ldap configurations

### PR DESCRIPTION
**Pull request by mestia**
Hello.
I've tried to move to the configuration some parameters to make the ldap provider work with standard LDAP tree without breaking the existing code.
Unfortunately some tests still fail, but It seems that the tests need to be updated.
The provider works on a live system with OpenLDAP.

Thanks, 
Alex

### CODE REVIEW

**Comment by bigpresh** [comment]
Um... apologies that this sat unmerged for so long :|  I've been meaning to get to it, but don't have an LDAP box to test against to be sure.  I'll see if I can figure out the remaining test failures and get it merged soon!

**Comment by mestia** [comment]
Absolutely no problem.Also I will be happy to test the final code for the LDAP provider.

**Comment by bigpresh** [comment]
Oh, my - this has been waiting far, far, far too long.

I still haven't had the tuits to get it passing tests; I believe I was planning to package the LDAP provider up as a separate CPAN dist anyway, so I may give that a shot.  I'd be very happy for it to be released by someone else who actively uses LDAP and can therefore properly test it, though!

**Comment by bigpresh** [comment]
In fact, the changes here look good, so I'm going to merge it as-is, then look at unbundling the LDAP provider from the main dist afterwards.  Thanks for the contribution, and sorry for the embarassing delay...

**Comment by mestia** [comment]
Cool! thanks!

**Pull request merged**
